flowchart TB
  Mulai-->Pengunjung
  Pengunjung-->SistemAntrean
  SistemAntrean-->Printer
  subgraph Pengunjung
    Orang-->p1("`Pilih Layanan`")
  end  
  subgraph SistemAntrean
    Sistem-->Layanan-->s("`Nomor Terakhir + 1`")-->s("`Simpan ke Database`")-->s("Cetak ke Printer`")
  end
  subgraph Printer
    Printer-->Cetak-->Nomor
  end
