flowchart TB
  Mulai-->Pengunjung
  Pengunjung-->SistemAntrean
  subgraph Pengunjung
    Orang-->p1("`Pilih Layanan`")
  end  
  subgraph SistemAntrean
    Sistem-->Layanan-->s1("`Nomor Terakhir + 1`")-->Printer-->Cetak
  end
